name: Docker

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        image:
          - {type: "samp", image: "linux", PREFIX: "", SUFFIX: "", context: "./samp/linux", platforms: "linux/amd64"}
          - {type: "samp", image: "wine", PREFIX: "", SUFFIX: "", context: "./samp/wine", platforms: "linux/amd64"}

          - {type: "node", image: "16", PREFIX: "node", SUFFIX: "", context: "./node", platforms: "linux/amd64,linux/arm64"}
          - {type: "node", image: "18", PREFIX: "node", SUFFIX: "", context: "./node", platforms: "linux/amd64,linux/arm64"}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: matthewp
          password: ${{ secrets.QUAY_SECRET }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.image.context }}
          file: ./${{ matrix.image.type }}/${{ matrix.image.image }}/Containerfile
          platforms: ${{ matrix.image.platforms }}
          push: true
          tags: |
            ghcr.io/matthewpi/images:${{ matrix.image.PREFIX }}${{ matrix.image.image }}${{ matrix.image.SUFFIX }}
            quay.io/matthewp/pterodactyl:${{ matrix.image.PREFIX }}${{ matrix.image.image }}${{ matrix.image.SUFFIX }}
